spring:
  rabbitmq:
    host: 192.168.252.230
    port: 5672
    virtual-host: /cej
    username: admin
    password: 123
    publisher-confirm-type: correlated #交换机确认
    publisher-returns: true #队列确认
    listener:
      simple:
        acknowledge-mode: manual  #把确认信息模式改成手动
